DefaultContentLanguage = "zh"
baseurl                = "https://eggroll.pages.dev/"
copyright              = "蛋卷儿"
enableGitInfo          = true                         # 启用 Git 信息
hasCJKLanguage         = true
languageCode           = "zh-cn"                      # 标准语言代码
theme                  = "hugo-theme-stack"
title                  = "蛋卷儿的博客"

[pagination]
    pagerSize = 5

[permalinks]
    page = "/:slug/"
    post = "/p/:slug/"

[params]
    favicon = "favicon.png"

    [params.footer]
        since = 2024

    [params.dateFormat]
        lastUpdated = "2006 年 1 月 2 日"
        published   = "2006 年 1 月 2 日"

    [params.sidebar]
        avatar   = "avatar.png"
        subtitle = "避嚣寻谧"

    [params.article]
        math = true
        toc  = true
        # readingTime = true
        wordCount = true

    [params.widgets]
        homepage = [
            { type = "archives", params = { limit = 5 } },
            { type = "categories", params = { limit = 10 } },
            { type = "search" },
            { type = "tag-cloud", params = { limit = 10 } },
        ]
        page = [{ type = "toc" }]

    [params.colorScheme]
        default = "auto"
        toggle  = true

    [params.comments]
        enabled = false

[menu]

    [[menu.social]]
        identifier = "github"
        name       = "GitHub"
        url        = "https://github.com/Jy-EggRoll"
        weight     = 99

        [menu.social.params]
            icon   = "brand-github"
            newTab = true

    [[menu.social]]
        identifier = "bilibili"
        name       = "哔哩哔哩"
        url        = "https://space.bilibili.com/165582851?spm_id_from=333.1007.0.0"
        weight     = 98

        [menu.social.params]
            icon   = "bilibili"
            newTab = true

    [[menu.social]]
        identifier = "mypage"
        name       = "我的网站"
        url        = "https://jy-eggroll.github.io/my-page/"
        weight     = 97

        [menu.social.params]
            icon   = "circle"
            newTab = true

[related]
    includeNewer = true
    toLower      = false

    [[related.indices]]
        name   = "tags"
        weight = 100

    [[related.indices]]
        name   = "categories"
        weight = 200

[markup.goldmark.extensions.passthrough]
    enable = true

[markup.goldmark.renderer]
    unsafe = true

[markup.tableOfContents]
    endLevel   = 4
    ordered    = false
    startLevel = 2

[markup.highlight]
    codeFences         = true
    guessSyntax        = true
    lineNos            = true
    lineNumbersInTable = true
    noClasses          = false

[frontmatter]
    lastmod = [":git", "lastmod"] # 优先使用 git 信息
